### ISSUE TITLE
Capabilities tests to mask assertions on legacy browsers

### ISSUE THREAD

**Issue by dwoldrich** [jamesshore/quixote#11]
I'm thinking something like Modernizr, but accessible out-of-the-box as "is*Supported" functions on the quixote or QFrame object.  

The intent is to know if browser functionality is available on the host and then be able to mask off assertions if that "is*Supported" function returns false.  I'm thinking gross feature support for things like Media Queries, flexbox, or CSS animations/transitions -- features that a well-developed, tested website might gracefully degrade from when they are absent from the host's CSS engine.

Taking media queries as an example, iff media queries are supported, then I would want to run my assertions for breakpoints other than the default breakpoint:

```
var fooEl = frame.get("#foo");

// large (default width) position should always be relative
frame.resize("1024px", "100%"); 
expect(fooEl.getRawStyle("position")).to.equal("relative");

// skip these assertions if media queries aren't supported on the host
if(quixote.areMediaQueriesSupported()) {
  // still in large down to 960px
  frame.resize("960px", "100%"); 
  expect(fooEl.getRawStyle("position")).to.equal("relative");

  // medium breakpoint at 959, change to position:fixed
  frame.resize("959px", "100%"); 
  expect(fooEl.getRawStyle("position")).to.equal("fixed");

  // still in medium down to 480
  frame.resize("480px", "100%"); 
  expect(fooEl.getRawStyle("position")).to.equal("fixed");

  // small, switch back to relative at 479
  frame.resize("479px", "100%"); 
  expect(fooEl.getRawStyle("position")).to.equal("relative");

  // it's turtles all the way down
  frame.resize("176px", "100%"); 
  expect(fooEl.getRawStyle("position")).to.equal("relative");
}
```

**Comment by jamesshore** [comment]
:+1:

Have you seen [quixote.browser](https://github.com/jamesshore/quixote/blob/master/docs/quixote.md#quixotebrowser)? That's basically the mechanism we have for this sort of thing. It only supports one check at the moment, though, and it's experimental.

**Comment by dwoldrich** [comment]
Ah, I missed that.  Yes, quixote.browser is exactly the kind of thing I was thinking of.  

Perhaps you might consider moving that object to QFrame though?  Capabilities can change depending on DOCTYPE selected and other web tchotchkes sprinkled in the head, and you might want to ask the frame what it thinks its capabilities are after the frame has fully loaded.

**Comment by jamesshore** [comment]
This is handled by `quixote.browser`, so I'm closing this issue. If there's specific feature detects you'd like to see added, please open an issue for each one.
