### ISSUE TITLE
Quixote as Karma Framework

### ISSUE THREAD

**Issue by jlink** [jamesshore/quixote#13]
Having a quixote available as karma framework to be loaded via npm and included in karma.conf.js would simplify the set up. See: https://www.npmjs.com/package/karma-jasmine-ajax as an example of what I'm thinking of.

**Comment by jamesshore** [comment]
Agreed. I'm thinking this would be best done as a separate project that linked this one as a peerDependency. I'm happy for someone else (like you?) to take it on. :-)

**Comment by woldie** [comment]
@jlink @jamesshore I've created a karma-quixote plugin.  It's works for my karma usecases.  Please try it out and let me know in the issues if it's not working for you.

npm install --save-dev karma-quixote
https://www.npmjs.com/package/karma-quixote

**Comment by jamesshore** [comment]
Awesome, thanks! I'll add that to the documentation.

**Comment by jamesshore** [comment]
I tested it and there were no problems. I'll add it to the v0.12 readme.

**Comment by jamesshore** [comment]
Released in v0.12.

**Comment by woldie** [comment]
It's happening!!!

![It's happening!!!](https://media4.giphy.com/media/5mBE2MiMVFITS/giphy.gif)
