### ISSUE TITLE
ReferenceError: before is not defined

### ISSUE THREAD

**Issue by devlemire** [jamesshore/quixote#35]
https://github.com/j-lemire/DevMtn-CSS-Store

I cannot get the unit tests to work to save my life, where am I going wrong?

If you pull down my repo, you can run 'npm run karma'

**Comment by jamesshore** [comment]
Jasmine uses `beforeAll` instead of `before`.

**Comment by j-lemire** [comment]
I've updated my syntax and now I have a new error that I cannot assert my element because it is undefined.

`describe("DevMtn-CSS-Store", function() {
	var frame, containerHeader;

	beforeAll(function() {
		frame = quixote.createFrame({
			src: "/"
		});
	});

	afterAll(function() {
		frame.remove();
	});

	beforeEach(function() {
		frame.reload();
		containerHeader = frame.get("#container-header");
	});

	it('Header container is 100% in width', function() {
		containerHeader.assert({
			width: '100%'
		}, "The header container should have a width of 100%");
	});
});`

**Comment by jamesshore** [comment]
`frame.reload` takes a callback (see [the docs](https://github.com/jamesshore/quixote/blob/master/docs/QFrame.md#framereload)), so you need to wait for the callback to finish before you run the tests:

```javascript
beforeEach(function(done) {
  frame.reload(function() {
    containerHeader = frame.get("#container-header");
    done();
  });
});
```

In Mocha, you can have multiple `beforeEach` functions, which makes this a bit cleaner. I'm not sure if it will work with Jasmine:

```javascript
beforeEach(function(done) {
  frame.reload(done);
});

beforeEach(function() {
  containerHeaer = frame.get("#container-header");
});
```

**Comment by jamesshore** [comment]
Closing on the assumption that this has been resolved.
