### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by wfsandoval12** [jamesshore/quixote#38]
I get this error when trying to run my first test. I have tried searching for solutions and most point to using npm to install browserify  and watchify but this doesn't seem to help either.

**Comment by jamesshore** [comment]
Try starting with the example code: https://github.com/jamesshore/quixote/tree/master/example

**Comment by jamesshore** [comment]
(The error you're getting is a result of not having a CommonJS module loader. If you're not familiar with CommonJS, it's hard to explain briefly. But the example project has everything already set up for you.)

**Comment by wfsandoval12** [comment]
I am already using karma for unit testing and now want to use quixote for css testing. I installed quixote via NPM and can't seem to get it working. I am using the same code from the example video just to see if I can get it running but I am getting the error specified above.

**Comment by jamesshore** [comment]
Your problem is most likely due to Karma mis-configuration. Did you run the example project?

(Not the example code in the video, but the whole project located in the /example directory.)

**Comment by jamesshore** [comment]
You can also use the karma-quixote plugin. If you do that, remove the `require("quixote")` line.

**Comment by jamesshore** [comment]
@wfsandoval12 I'm closing this issue due to lack of response. If you still need help, please re-open it.
