### ISSUE TITLE
Add Nightmare to test suite

### ISSUE THREAD

**Issue by darlanmendonca** [jamesshore/quixote#49]
Is useful add nightmare browser to test suite?

I'm looking for tools for tests, overall, and nightmare can be 2x more fast than Phantomjs.

here => https://github.com/segmentio/nightmare

**Comment by jamesshore** [comment]
We're not adding any headless browsers to our test suite at this time. The purpose of Quixote is to test how sites display on users' real browsers, so testing on a headless browser defeats the purpose.

That said, it looks like Nightmare uses Electron under the covers, which in turn uses Chromium. It's likely to work just fine even if it's not officially supported.
