### ISSUE TITLE
Fail fast when creating a frame with a non-existent HTML or CSS file

### ISSUE THREAD

**Issue by bjornicus** [jamesshore/quixote#5]
I had set up a new project to see what it would be like to actually use Quixote to develop a page, but hadn't set up my paths right so the html file I was trying to use as 'src' in a quixote.createFrame call, so it wasn't actually finding the file, but the error I was getting was when I tried to do a getElement and didn't find the expected element. 

the following pull request addresses this issue by checking for the existence of the thing referred to by 'src' or 'stylesheet' when createFrame is called:
https://github.com/jamesshore/quixote/pull/4

**Comment by jamesshore** [comment]
Fix reinstated in v0.9.0.
