### ISSUE TITLE
Example project is out of date with respect to documentation

### ISSUE THREAD

**Issue by amoe** [jamesshore/quixote#50]
Hi, first of all thanks for Quixote!

It seems that there is a bit of a deviation between the configuration for the example project and the configuration described in README.md.  The README describes a configuration with karma, chai, using the karma framework support for both -- which seems like a more modern configuration.  The example project uses the commonjs framework in karma, and loads quixote and chai from files under the `vendor` subdirectory.  This necessitates some specific preprocessor configuration, that's not described by the documentation for Quixote itself.  Since `karma-commonjs` is not referenced by the Quixote docs, the user has to figure that out themselves.  Also, when using the example project, the `assert.equal` style shown by the README will not work if the user modifies the example, as it needs test runner support from the `chai` framework.

I eventually pieced together a configuration for integration testing that didn't seem to need `karma-commonjs` at all: https://github.com/amoe/quixote-jekyll  (Note that this is just a simple stub test for the default Jekyll blog configuration and isn't self-contained like a real example project would be.)

That configuration seems very different from the one given in the example project, although I'm not sure which one would be considered advisable.  Although it's arguable that these are just details of the configuration of separate projects, I think it would be worth giving a usable example of the style demonstrated in the README, because the configuration of the various parts can be a bit overwhelming for a new user.

**Comment by jamesshore** [comment]
Thanks for your thoughts. Quixote allows you to use any tools and configuration you like, and the specifics of module loaders, etc., is outside our scope.
