### ISSUE TITLE
Still alive

### ISSUE THREAD

**Issue by Anachron** [jamesshore/quixote#9]
Hey there, I do like the idea of css unit testing and I'm asking myself if this project is still alive? There were some features left from your blog posts and I really wish you would not discontinuw it.

**Comment by jamesshore** [comment]
It's still alive. :-) Is there a specific feature you're looking for?

**Comment by JayBazuzi** [comment]
It's already a triumph. A huge success.

-J on a mobile device

**Comment by jamesshore** [comment]
It's hard to overstate my satisfaction.

**Comment by Anachron** [comment]
So do you mind linking some projects using it? I was thinking about using it but the lack of activity made me wonder.

About the missing feature I cannot say yet, will have to install it first ;)

**Comment by jamesshore** [comment]
I don't know which projects are using it, if any. Sorry!
